* Базовые операции с git
2024-06-11

** Ветки

Пока у тебя одна ветка - main, там будет парадный проверенный код.
Чтобы что-то исправить делают новую ветку - брэнч (branch), отпочковывая её от основной.
Там что-то исправляют и всё проверяют и затем сливают (merge) в основную ветку и эту временную ветку удаляют.
Если над исправлением нужно работать долго и серьёзно, то также её пушат на сервер, или не пушат если исправлние простое и сделать его быстро.
Если исправление не удалось, эту ветку удаляют и делаю новую и новую попытку.


- написать что-нибудь осмысленное в README (что-то про проект) в локальном каталоге
- закоммитить локально и запушить на github
- сделать ветку (локально) от основной ветки main, например назвать fix (исправление)
- дописать что-нибудь ещё в README (в этой ветке), закоммитить локально, НЕ ПУШИТЬ в github
- слить изменения в ветку main
- удалить ветку fix
- запушить изменеия в main на github
- удалить ненужную ветку fix


* Приложние gtk+
2024-06-17

- взять всё тот же пример ex1.py (я его залил в репо) и убрать  всё лишнее
- для того, чтобы показывать инфу о файлах, добавить на панель компонент ListView
   https://python-gtk-3-tutorial.readthedocs.io/en/latest/treeview.html
   https://habr.com/ru/articles/740178/
- научиться с ним работать - просто написать любой текст во все колонки
  
